name: UpdateDependabotPR

on:
  pull_request_target:
    branches: [ main ]

jobs:
  pyiron:
    uses: pyiron-node-store/actions/.github/workflows/dependabot-pr.yml@actions-4.0.2
    secrets: inherit

