name: Entry Point tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  entry_point_matrix:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.12'
          label: osx-64-py-3-12

        - operating-system: windows-latest
          python-version: '3.12'
          label: win-64-py-3-12

        - operating-system: ubuntu-latest
          python-version: '3.12'
          label: linux-64-py-3-12

        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11

        - operating-system: ubuntu-latest
          python-version: '3.10'
          label: linux-64-py-3-10

    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      shell: bash -l {0}
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment.yml
    - name: Test no entry point
      shell: bash -l {0}
      timeout-minutes: 10
      run: |
        python -m unittest tests/test_packages/test_no_entry_point.py
    - name: Install test_a
      shell: bash -l {0}
      run: pip install tests/test_packages/test_a
    - name: Test_a entry point
      shell: bash -l {0}
      timeout-minutes: 10
      run: |
        python -m unittest tests/test_packages/test_a_entry_point.py
