# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron-node-store/actions/.github/workflows/push-pull.yml@actions-4.0.2
    secrets: inherit
    with:
      docs-env-files: .ci_support/environment.yml
      notebooks-env-files: .ci_support/environment.yml
      extra-python-paths: tests tests/benchmark tests/integration tests/static tests/unit  # For executorlib
      python-version-alt2: 'exclude'  # No python 3.10
      python-version-alt3: '3.13'  # Use python 3.13 instead of python 3.9
      alternate-tests-env-files: .ci_support/lower_bound.yml
      alternate-tests-python-version: '3.12'
      alternate-tests-dir: tests/unit
      do-codecov: true
      do-codacy: false
      do-coveralls: false

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mypy
        run: pip install mypy
      - name: Test
        run: mypy --ignore-missing-imports --strict-equality ${{ github.event.repository.name }}

  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check

  ruff-sort-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check --select I --fix --diff

